import React from 'react';
import {
  ArrowLeft, Shield, Globe, Brain, Check
} from 'lucide-react';

export default function AIAgentsPage({ onBack }) {
  const agents = [
    {
      id: 'detector',
      title: 'Synthetic Template Detector',
      role: 'Analyze resume composition patterns',
      icon: Shield,
      color: '#db2777',
      bg: 'rgba(219, 39, 119, 0.05)',
      highlights: [
        'Recognizes standard AI-generated resume layout frameworks.',
        'Flags common AI vocabulary patterns (e.g., "delve", "tapestry", "tapestry of skills").',
        'Scans hidden resume layers for invisible text injections.'
      ],
      description: 'The Detector Agent scans the uploaded document metadata and sentence structure. It evaluates semantic predictability and flags resumes generated by ChatGPT or other AI engines.'
    },
    {
      id: 'osint',
      title: 'OSINT Footprint Verifier',
      role: 'Verify credentials and history online',
      icon: Globe,
      color: '#2563eb',
      bg: 'rgba(37, 99, 235, 0.05)',
      highlights: [
        'Crawls public developer repositories and GitHub contributions.',
        'Verifies employment claims against web footprint indexes.',
        'Matches social profile identity parameters to avoid impersonation.'
      ],
      description: 'The OSINT Agent crawls the web to check candidate claims. It ensures work histories, projects, and online footprints match claims on the resume.'
    },
    {
      id: 'pow',
      title: 'Proof of Work Telemetry Agent',
      role: 'Validate human interaction behaviors',
      icon: Brain,
      color: '#059669',
      bg: 'rgba(5, 150, 105, 0.05)',
      highlights: [
        'Generates logic/code challenges relevant to resume skills.',
        'Detects instant clipboard copy-paste events (ChatGPT bypass).',
        'Analyzes typing keypress intervals to ensure human origins.'
      ],
      description: 'The Telemetry Agent verifies the candidate through a reasoning challenge. It captures interaction rhythm data to distinguish real human developers from scripts.'
    }
  ];

  return (
    <div className="min-h-screen bg-white text-neutral-900 flex flex-col" style={{ fontFamily: 'var(--font-sans)' }}>

      <header className="h-16 shrink-0 flex items-center justify-between px-6 border-b border-neutral-100 sticky top-0 bg-white/90 backdrop-blur-md z-40">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="p-1.5 rounded-lg border border-neutral-200 hover:bg-neutral-50 text-neutral-600 hover:text-neutral-900 transition-colors"
            aria-label="Back to home"
          >
            <ArrowLeft size={16} />
          </button>
          <div onClick={onBack} className="flex items-center gap-2 cursor-pointer">
            <svg width="20" height="24" viewBox="0 0 44 54" fill="none">
              <defs>
                <linearGradient id="agents-g-back" x1="6" y1="6" x2="20" y2="48" gradientUnits="userSpaceOnUse">
                  <stop offset="0%" stopColor="#1565C0" />
                  <stop offset="100%" stopColor="#1E88E5" />
                </linearGradient>
                <linearGradient id="agents-g-front" x1="22" y1="2" x2="34" y2="46" gradientUnits="userSpaceOnUse">
                  <stop offset="0%" stopColor="#26C6DA" />
                  <stop offset="100%" stopColor="#1565C0" />
                </linearGradient>
              </defs>
              <rect x="4" y="6" width="17" height="40" rx="8.5" fill="url(#agents-g-back)" transform="rotate(14 12.5 26)" />
              <rect x="20" y="3" width="15" height="38" rx="7.5" fill="url(#agents-g-front)" transform="rotate(-6 27.5 22)" />
            </svg>
            <span className="font-bold text-base tracking-tight" style={{ letterSpacing: '-0.6px' }}>picket</span>
            <span className="text-xs bg-neutral-100 text-neutral-600 px-2 py-0.5 rounded-full font-mono font-bold uppercase tracking-wider text-[9px]">
              Agents
            </span>
          </div>
        </div>
        <button onClick={onBack} className="text-xs font-semibold text-neutral-600 hover:text-neutral-900 transition-colors">
          Exit to Home
        </button>
      </header>

      <main className="flex-1 max-w-[1000px] mx-auto w-full px-6 py-16">
        <div className="text-center max-w-xl mx-auto mb-16">
          <span className="text-xs font-mono font-bold text-emerald-600 uppercase tracking-wider">Verification Engines</span>
          <h1 className="text-4xl font-extrabold tracking-tight text-neutral-900 mt-2 mb-4 leading-none">
            Meet the Screening Agents
          </h1>
          <p className="text-sm text-neutral-600 leading-relaxed">
            Picket orchestrates three background agents to verify applicant credibility and filter out bots.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {agents.map((agent) => {
            const Icon = agent.icon;
            return (
              <div
                key={agent.id}
                className="bg-white p-6 rounded-2xl border border-neutral-200 flex flex-col justify-between shadow-sm hover:shadow-md transition-all duration-200"
              >
                <div>

                  <div className="flex justify-between items-center mb-6">
                    <span
                      className="w-10 h-10 rounded-xl flex items-center justify-center"
                      style={{ backgroundColor: agent.bg, color: agent.color }}
                    >
                      <Icon size={20} />
                    </span>
                    <span className="text-[9px] font-mono font-bold uppercase tracking-widest text-neutral-400">
                      ACTIVE SYSTEM
                    </span>
                  </div>

                  <h3 className="text-lg font-bold tracking-tight text-neutral-900 mb-1">{agent.title}</h3>
                  <p className="text-xs text-neutral-400 font-semibold mb-4">{agent.role}</p>
                  <p className="text-xs text-neutral-600 leading-relaxed mb-6">{agent.description}</p>

                  <div className="border-t border-neutral-100 pt-5 mt-4">
                    <span className="text-[10px] font-mono font-bold text-neutral-400 uppercase tracking-widest block mb-3">
                      Key Checks
                    </span>
                    <ul className="space-y-3">
                      {agent.highlights.map((highlight, idx) => (
                        <li key={idx} className="flex gap-2 text-xs text-neutral-600">
                          <Check size={14} className="text-neutral-400 shrink-0 mt-0.5" />
                          <span>{highlight}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <div className="mt-16 bg-neutral-950 text-white rounded-2xl p-6 md:p-8 border border-neutral-900 space-y-6">
          <div>
            <h3 className="text-lg font-bold tracking-tight text-white mb-2">Analyzing Interaction Telemetry</h3>
            <p className="text-xs text-neutral-400 leading-relaxed max-w-xl">
              Unlike static tests, our Proof of Work challenges capture candidate interaction telemetry. Here is how we differentiate between humans and AI-assisted scripts:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-neutral-900">

            <div className="space-y-3 bg-neutral-900/50 p-4 rounded-xl border border-neutral-900">
              <div className="flex justify-between items-center">
                <span className="text-xs font-semibold text-emerald-400 font-mono">ORGANIC HUMAN BEHAVIOR</span>
                <span className="text-[9px] font-mono bg-emerald-950 text-emerald-400 px-2 py-0.5 rounded-full">APPROVED</span>
              </div>
              <div className="h-20 bg-neutral-950 rounded border border-neutral-900 p-2 flex items-end gap-0.5">
                {[20, 45, 15, 60, 30, 25, 80, 50, 40, 10, 35, 75, 45, 20, 65, 30, 90, 50, 30, 15, 40].map((h, i) => (
                  <div key={i} className="flex-1 bg-emerald-500/80 rounded-t" style={{ height: `${h}%` }} />
                ))}
              </div>
              <p className="text-[11px] text-neutral-400 leading-relaxed">
                <strong>Natural Typing Cadence:</strong> Variations in latency between characters (50ms to 400ms), error correction delays, and manual phrasing entropy verify a human is typing the solution.
              </p>
            </div>

            <div className="space-y-3 bg-neutral-900/50 p-4 rounded-xl border border-neutral-900">
              <div className="flex justify-between items-center">
                <span className="text-xs font-semibold text-red-400 font-mono">AUTOMATED BOT BEHAVIOR</span>
                <span className="text-[9px] font-mono bg-red-950 text-red-400 px-2 py-0.5 rounded-full">REJECTED</span>
              </div>
              <div className="h-20 bg-neutral-950 rounded border border-neutral-900 p-2 flex items-end gap-0.5">
                {[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5].map((h, i) => (
                  <div key={i} className="flex-1 bg-red-500/80 rounded-t" style={{ height: `${h}%` }} />
                ))}
              </div>
              <p className="text-[11px] text-neutral-400 leading-relaxed">
                <strong>Bot/Script Telemetry:</strong> Instant copy-paste events (0ms delay) or microsecond-level uniform typing frequencies indicate automated solutions.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
